config/routes.rb
Qrtime::Application.routes.draw do



  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}


  resources :student_activities do
    member do
      get :confirmation_in
      get :confirmation_out
    end
    collection do
      post :check_in
      post :check_out
    end

  end


  resources :requests do
    get 'read'
  end


  resources :course_sessions do
    get 'check_in'
    get 'check_out'
  end


  resources :courses do
  member do
    get :roll
  end
  end


  devise_for :users   
  resources :users do
    member do
      get :courses
      post :course_add
      post :course_remove
    end

  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    Time.zone = 'Eastern Time (US & Canada)'
    @users = User.all
    @user = current_user
    if current_user.has_role?(:instructor) == true
       @courses = Course.all(:conditions => {:instructor => current_user.id})
       @course_sessions = CourseSession.all(:conditions => {:course_id => @courses})
    elsif current_user.has_role?(:student) == true
      @courses = @user.courses
    end

    @student_activities = StudentActivity.find_all_by_user_id(@user)
    @caldate = params[:month] ? Date.parse(params[:month]) : Date.today
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h3>Home</h3>

<% if user_signed_in? %>

    <% if current_user.has_role?(:student) == true  %>
        <table border="1">
          <tr>
            <th>Course</th>
            <th>Date</th>
            <th>Start Time</th>
            <th>Check-In</th>

          </tr>

          <% @courses.each do |c| %>
                <% cs = c.valid_sessions %>
                <% cs.each do |s| %>
                <% sa = s.student_activities.all(:conditions => ["user_id = ?", @user.id]) %>
                <% if sa.length == 0 %>
                      <tr class = "absent">
                <% elsif sa.length == 1 %>
                      <tr class = "late">
                <% else %>
                    <% classlength = s.end_time - s.start_time %>
                    <% inclass = sa.last.time - sa.first.time %>
                      <% if inclass < classlength  && (classlength-inclass) > 5 %>
                          <tr class = "late">
                      <% else %>
                          <tr class = "present">
                      <% end %>
                <% end %>

                    <td><%= link_to s.course.name, c.check_in_url %></td>
                    <td><%= s.date %></td>
                    <td><%= s.start_time.strftime("%I:%M:%S") %></td>
                    <% if sa.length > 0 %>
                        <td><%= sa.first.time.strftime("%I:%M:%S") %></td>
                    <% end %>
                    <% if sa.length == 0 && 1 == 0 %>
                      <td></td>
                      <td></td>
                      <%= simple_form_for(@student_activity) do |f| %>
                          <%= f.error_notification %>

                           <td><%= f.input :excuse %>
                            <%= f.submit "Submit Absence Excuse" %></td>

                      <% end %>

                    <% end %>
                  </tr>

              <% end %>
          <% end %>
        </table> 
    <% end %>

    <% if current_user.has_role?(:instructor) == true  %>
        <% @courses.each do |course|  %>
            <tr>
              <td><%= link_to(course.name, course) %></td>
            </tr>
            <br>
        <% end %>
        <br>
        <%= link_to 'New Course', new_course_path %>

        <% if @courses.length > 0 %>




            <div id="calendar">
              <h2 id="month">

                <%= link_to "<", :month => (@caldate.beginning_of_month-1).strftime("%Y-%m-%d") %>
                <%=h @caldate.strftime("%B %Y") %>
                <%= link_to ">", :month => (@caldate.end_of_month+1).strftime("%Y-%m-%d") %>

              </h2>
              <%= calendar_for(@course_sessions, :year => @caldate.year, :month => @caldate.month) do |calendar| %>
                  <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
                  <%= calendar.day do |day, coursesessions| %>
                      <%= day.day %>
                      <ul>
                        <% coursesessions.each do |coursesession| %>
                            <li><%= link_to h(coursesession.course.name), coursesession %></li>
                        <% end %>
                      </ul>
                  <% end %>
              <% end %>
            </div>



        <% end %>


    <% end %>
    <br><br>

    <% if current_user.has_role?(:admin) == true %>

        <%= link_to 'Users', users_path %> <br>
        <%= link_to 'Courses', courses_path %> <br>


    <% end %>


<% else %>
    <%= link_to 'Login', new_user_session_path %>
    <br>
    <%= link_to 'Sign Up', new_user_registration_path %>

<% end %>