config/routes.rb
Qrtime::Application.routes.draw do



  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}


  resources :student_activities do
    member do
      get :confirmation_in
      get :confirmation_out
    end
    collection do
      post :check_in
      post :check_out
    end

  end


  resources :requests do
    get 'read'
  end


  resources :course_sessions do
    get 'check_in'
    get 'check_out'
  end


  resources :courses do
  member do
    get :roll
  end
  end


  devise_for :users   
  resources :users do
    member do
      get :courses
      post :course_add
      post :course_remove
    end

  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"


end

app/models/course_session.rb
class CourseSession < ActiveRecord::Base
  after_save :set_checkin
  resourcify
  attr_accessible :course_id, :date, :end_time, :start_time, :description, :check_in_url, :check_out_url

  validates_presence_of :course_id, :date, :end_time, :start_time
  belongs_to :course
  has_many :student_activities

  def set_checkin 
  	self.check_in_url = "https://tufts.qualtrics.com/SE/?SID=SV_54lHEJAekyaMic5&Speaker=#{self.course.instructor}&Date=#{self.date.strftime("%m-%Y")}&Title=#{self.course.name}"
  end 

end

app/controllers/course_sessions_controller.rb
class CourseSessionsController < ApplicationController
  before_filter :authenticate_user!
  # GET /course_sessions
  # GET /course_sessions.json
  def index
 #   authorize! :index, @user, :message => 'Not authorized.'
    @course_sessions = CourseSession.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @course_sessions }
    end
  end

  # GET /course_sessions/1
  # GET /course_sessions/1.json
  def show
    Time.zone = 'Eastern Time (US & Canada)'
#    authorize! :show, @user, :message => 'Not authorized.'
    @course_session = CourseSession.find(params[:id])
    @student_activities = StudentActivity.all(:conditions => {:course_session_id => @course_session.id})
    @course = @course_session.course
    @users = @course.users

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course_session }
    end
  end

  # GET /course_sessions/new
  # GET /course_sessions/new.json
  def new
 #   authorize! :new, @user, :message => 'Not authorized.'
    @course_session = CourseSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course_session }
    end
  end

  # GET /course_sessions/1/edit
  def edit
#    authorize! :edit, @user, :message => 'Not authorized.'
    @course_session = CourseSession.find(params[:id])
  end

  # POST /course_sessions
  # POST /course_sessions.json
  def create
 #   authorize! :create, @user, :message => 'Not authorized.'
    @course_session = CourseSession.new(params[:course_session])

    respond_to do |format|
      if @course_session.save
        format.html { redirect_to @course_session, notice: 'Course session was successfully created.' }
        format.json { render json: @course_session, status: :created, location: @course_session }
      else
        format.html { render action: "new" }
        format.json { render json: @course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /course_sessions/1
  # PUT /course_sessions/1.json
  def update
 #   authorize! :update, @user, :message => 'Not authorized.'
    @course_session = CourseSession.find(params[:id])

    respond_to do |format|
      if @course_session.update_attributes(params[:course_session])
        format.html { redirect_to @course_session, notice: 'Course session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_sessions/1
  # DELETE /course_sessions/1.json
  def destroy
 #   authorize! :destroy, @user, :message => 'Not authorized.'
    @course_session = CourseSession.find(params[:id])
    @course_session.destroy

    respond_to do |format|
      format.html { redirect_to course_url(@course_session.course) }
      format.json { head :no_content }
    end
  end

  def check_in
    @course_session = CourseSession.find(params[:course_session_id])
    @user = current_user
    @course = @course_session.course

    @student_activity = StudentActivity.new
    @student_activity.course_session_id = @course_session.id

	
    respond_to do |format|
      format.html
      format.svg  { render :qrcode => course_session_check_in_url(@course_session)}
    end
  end

  def check_out
    @course_session = CourseSession.find(params[:course_session_id])

    @student_activity = StudentActivity.new
    @student_activity.course_session_id = @course_session.id


    respond_to do |format|
      format.html
      format.svg  { render :qrcode => course_session_check_out_url(@course_session) }
    end
  end

end

app/helpers/course_sessions_helper.rb
module CourseSessionsHelper
end

app/views/course_sessions/_form.html.erb
<%= simple_form_for(@course_session) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :course %>
    <%= f.input :date %>
    <%= f.input :description %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/course_sessions/check_in.html.erb
<% if current_user.has_role?(:student) == true %>

<% if current_user.enrolled_in?(@course_session.course) == false %>
          <% @user.courses << @course %>
<% end %>

      <% if current_user.student_activities.all(:conditions => {:course_session_id => @course_session.id, :action => "Check-In"}).length > 0 %>
              You have already checked in to this course session.
                  <%= link_to 'Continue to Survey', @course_session.set_checkin %>
      <% else %>
             <%= form_for @student_activity, :url => {:controller => :student_activities, :action => "check_in"} do |f|  %>
            <%=  f.hidden_field :course_session_id %>
            <%= f.submit "Check In to " + @course_session.course.name, :class => 'checkbutton'  %>
       <% end %>
    <% end %>



<% elsif current_user.has_role?(:instructor) == true %> <br><br>
    You are an instructor. Here is the QR code for students to check in to <%= @course_session.course.name %> . <br><br>
    <%=  image_tag( course_session_check_in_url(@course_session, :format => :svg)) %>
       <br><br>
    <%= link_to 'Home', root_path %>

<% elsif current_user.has_role?(:admin) == true %>   <br><br>
     You are an admin. Here is the QR code for students to check in to <%= @course_session.course.name %> . <br><br>
    <%=  image_tag( course_session_check_in_url(@course_session, :format => :svg)) %>.
       <br><br>
    <%= link_to 'Home', root_path %>
<% end %>

app/views/course_sessions/check_out.html.erb
<% if current_user.has_role?(:student) == true %>
    <% if current_user.student_activities.all(:conditions => {:course_session_id => @course_session.id, :action => "Check-In"}).length == 0 %>
        You have not checked in to this course session yet. You need to check in before you can check out.
        <br><br><%= link_to 'Home', root_path %>
    <% else %>
        <% if current_user.student_activities.all(:conditions => {:course_session_id => @course_session.id, :action => "Check-Out"}).length > 0 %>
            You have already checked out of this course session.
            <% if  @course_session.check_out_url != "" %>
                <%= link_to 'Continue to Qualtrics', @course_session.check_out_url %>
            <% else %>
                <br><br><%= link_to 'Home', root_path %>
            <% end %>
        <% else %>
        <%= form_for @student_activity, :url => {:controller => :student_activities, :action => "check_out"} do |f|  %>
            <%=  f.hidden_field :course_session_id %>
            <%= f.submit "Check Out of " + @course_session.course.name, :class => 'checkbutton'%>
            <% end %>
        <% end %>
     <% end %>


<% elsif current_user.has_role?(:instructor) == true %> <br><br>
    You are an instructor. Here is the QR code for students to check out of <%= @course_session.course.name %> . <br><br>
    <%=  image_tag( course_session_check_out_url(@course_session, :format => :svg)) %>
    <br><br>
    <%= link_to 'Home', root_path %>

<% elsif current_user.has_role?(:admin) == true %>   <br><br>
    You are an admin. Here is the QR code for students to check out of <%= @course_session.course.name %> . <br><br>
    <%=  image_tag( course_session_check_out_url(@course_session, :format => :svg)) %>.
    <br><br>
    <%= link_to 'Home', root_path %>
<% end %>

app/views/course_sessions/edit.html.erb
<h1>Editing course_session</h1>

<%= render 'form' %>
|
<%= link_to 'Back', course_session_path(@course_session) %>

app/views/course_sessions/index.html.erb
<h1>Listing course_sessions</h1>

<table>
  <tr>
    <th>Course</th>
    <th>Date</th>
    <th>Start time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @course_sessions.each do |course_session| %>
  <tr>
    <td><%= course_session.course.name %></td>
    <td><%= course_session.date %></td>
    <td><%= course_session.start_time.strftime("%I:%M:%S") %></td>
    <td><%= course_session.end_time.strftime("%I:%M:%S") %></td>
    <td><%= link_to 'Show', course_session %></td>
    <td><%= link_to 'Edit', edit_course_session_path(course_session) %></td>
    <td><%= link_to 'Destroy', course_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course session', new_course_session_path %>

app/views/course_sessions/new.html.erb
<h1>New Course Session</h1>

<%= render 'form' %>

<!--should link to course last visited-->
<%= link_to 'Back', root_path %>

app/views/course_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Course:</b>
  <%= @course_session.course.name %>
</p>

<p>
  <b>Date:</b>
  <%= @course_session.date %>
</p>

<p>
  <b>Description:</b>
  <%= @course_session.description %>
</p>

<p>
  <b>Start time:</b>
  <%= @course_session.start_time.strftime("%I:%M:%S") %>
</p>

<p>
  <b>End time:</b>
  <%= @course_session.end_time.strftime("%I:%M:%S")  %>
</p>

<div id="qr"><%= link_to (image_tag(course_session_check_in_url(@course_session, :format => :svg))),
                      course_session_check_in_url(@course_session)%></div> 
<div id="whatever" style="display:none">
  <table border="1">
    <tr>
      <th>Student</th>
      <th>Check-In</th>
      <th>Check-Out</th>
      <th>% Attended</th>

    </tr>
     <% if @users.length != 0 %>
        <% @users.each do |u| %>
            <% sa = u.student_activities.all(:conditions => ["course_session_id = ?", @course_session.id, ]) %>
            <% if sa.length == 0 %>
                <tr class = "absent">
                <% pa = 0 %>
            <% elsif sa.length == 1 %>
                <tr class = "late">
                <% pa = "n/a" %>
            <% else %>
                <% classlength = @course_session.end_time - @course_session.start_time %>
                <% inclass = sa.last.time - sa.first.time %>
                <% pa = ((inclass/classlength).round(2))*100 %>
                <% if pa>100 %>
                    <% pa = 100 %>
                <% end %>
                <% if inclass < classlength && (classlength-inclass) > 5 %>
                    <tr class = "late">
                <% else %>
                    <tr class = "present">
                <% end %>
            <% end %>

            <td><%= u.name %></td>
            <% if sa.length > 0 %>
                <td><%= sa.first.time.strftime("%I:%M:%S") %></td>
            <% else %>
                <td></td>
                <td></td>
            <% end %>
            <% if sa.length > 1 %>
                <td><%= sa.last.time.strftime("%I:%M:%S") %></td>
            <% elsif sa.length == 1 %>
            <td></td>
            <% end %>
            <td><%= pa %></td>
            </tr>

        <% end %>
    <% end %>
  </table>


</div>


<br><br>
<%= link_to 'Edit', edit_course_session_path(@course_session) %>
<%= link_to 'Destroy', @course_session, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Back', course_path(@course_session.course) %>