config/routes.rb
Qrtime::Application.routes.draw do



  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}


  resources :student_activities do
    member do
      get :confirmation_in
      get :confirmation_out
    end
    collection do
      post :check_in
      post :check_out
    end

  end


  resources :requests do
    get 'read'
  end


  resources :course_sessions do
    get 'check_in'
    get 'check_out'
  end


  resources :courses do
  member do
    get :roll
  end
  end


  devise_for :users   
  resources :users do
    member do
      get :courses
      post :course_add
      post :course_remove
    end

  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!
  # GET /courses
  # GET /courses.json
  def index
  #  authorize! :index, @user, :message => 'Not authorized.'
    @courses = Course.all
    @course_sessions = CourseSession.all
    @caldate = params[:month] ? Date.parse(params[:month]) : Date.today

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    Time.zone = 'Eastern Time (US & Canada)'
   # authorize! :index, @user, :message => 'Not authorized.'
    @course = Course.find(params[:id])
    @course_sessions = @course.course_sessions
    @users = @course.users

    @all_users = User.with_role :student
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
      format.csv # show.cvs.erb
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    #authorize! :new, @user, :message => 'Not authorized.'
    @course = Course.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    #authorize! :edit, @user, :message => 'Not authorized.'
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    #authorize! :create, @user, :message => 'Not authorized.'
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    #authorize! :update, @user, :message => 'Not authorized.'
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
   #authorize! :destroy, @user, :message => 'Not authorized.'
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  
end

# # GET /courses/1/roll
# def roll
#   @course = Course.find(params[:id])
# end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%=  f.input :instructor %>
    <%= f.input :check_in_url, :label => "Edit Default Survey" %> 
    <%= f.association :users, label: "Add Students", collection: (User.with_role :student), as: :check_boxes %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>


<%= link_to 'Back', course_path(@course) %>

app/views/courses/index.html.erb
<h1>Courses:</h1>

<table>


<% @courses.each do |course| %>
  <tr>
    <td><%= link_to(course.name, course) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

<br>
<br>
<% if @courses.length > 0 %>




    <div id="calendar">
      <h2 id="month">

        <%= link_to "<", :month => (@caldate.beginning_of_month-1).strftime("%Y-%m-%d") %>
        <%=h @caldate.strftime("%B %Y") %>
        <%= link_to ">", :month => (@caldate.end_of_month+1).strftime("%Y-%m-%d") %>

      </h2>
      <%= calendar_for(@course_sessions, :year => @caldate.year, :month => @caldate.month) do |calendar| %>
          <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
          <%= calendar.day do |day, coursesessions| %>
              <%= day.day %>
              <ul>
                <% coursesessions.each do |coursesession| %>
                    <li><%= link_to h(coursesession.course.name), coursesession %></li>
                <% end %>
              </ul>
          <% end %>
      <% end %>
    </div>



<% end %>


<%= link_to 'Back', root_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/courses/show.csv.erb
<% title = [@course.name] %>
<%= CSV.generate_line title, {:row_sep => nil} %>
<% headers = ["Session", "Date", "Start Time", "End Time", "Student", "Check In", "Check Out", "Percent Attended"] %>
<%= CSV.generate_line headers, {:row_sep => nil} %>
<% count = 0 %>
<% @course_sessions.each do |session| %>
    <% count = count +1 %>
    <% @users.each do |user| %>
        <% sa = user.student_activities.all(:conditions => ["course_session_id = ?", session.id, ]) %>
        <% if sa.length == 0 %>
              <% checkin = "n/a" %>
              <% checkout = "n/a" %>
              <% pa = 0 %>
        <% elsif sa.length == 1 %>
            <% checkin = sa.first.time.strftime("%I:%M:%S") %>
            <% checkout = "n/a" %>
            <% pa = "n/a" %>
        <% else %>
            <% checkin = sa.first.time.strftime("%I:%M:%S") %>
            <% checkout = sa.last.time.strftime("%I:%M:%S")  %>
            <% classlength = session.end_time - session.start_time %>
            <% inclass = sa.last.time - sa.first.time %>
            <% pa = ((inclass/classlength).round(2))*100 %>
            <% if pa>100 %>
                <% pa = 100 %>
            <% end %>
        <% end %>
        <% row = [ count,
                    session.date,
                    session.start_time.strftime("%I:%M:%S"),
                    session.end_time.strftime("%I:%M:%S"),
                    user.name,
                    checkin,
                    checkout,
                    pa
                        ] %>
        <%=   CSV.generate_line row, {:row_sep => nil} %>
    <% end %>
<% end %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to "Download Course Data", {:controller => "courses", :action => "show", :id => @course, :format => "csv"}, {:class => 'databutton'} %>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Instructor:</b>
  <%=@course.instructor %> 
</p>

<p>

    <table border="1">
      <tr>
        <th>Course Session</th>
        <th>Date</th>
        <th>Start Time</th>
        <th>End Time</th>

      </tr>
      <% count = 1 %>
  <% @course_sessions.each do |course_session| %>


      <tr>
        <td><%= link_to(count, course_session) %></td>
        <td><%= course_session.date %></td>
        <td><%= course_session.start_time.strftime("%I:%M:%S") %></td>
        <td><%= course_session.end_time.strftime("%I:%M:%S") %></td>
      </tr>
        <% count = count+1  %>

  <% end %>
    </table>
</p>

<%= link_to 'New Course session', new_course_session_path %>

<br><br>

<p>
  <b>Students Enrolled:</b> <br>
  <% @users.each do |u|%>
     <%= link_to u.name, u %><br>
  <% end %>
</p>



<br>
<br>

<%= link_to 'Edit', edit_course_path(@course) %>
<%= link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Back', root_path %>